eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
app.name=stack-sentinel
logging.file.name=/usr/apps/logs/${app.name}.log
logging.file.path=/usr/apps/logs
logging.logback.rollingpolicy.file-name-pattern=${logging.file.path}/${app.name}/%d{yyyy-MM-dd}/${app.name}.%d{yyyy-MM-dd}.%i.log.gz
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.total-size-cap=100GB
logging.logback.rollingpolicy.max-history=1095