server.port=5999
server.servlet.context-path=/stack-sentinel/
spring.application.name=stack-sentinel
spring.jpa.hibernate.ddl-auto=update
logging.file.name=/usr/apps/logs/stack-sentinel.log
logging.file.path=/usr/apps/logs
logging.level.root=INFO
# Logging pattern with MDC trace_id
# For console logs
logging.pattern.console=time=%d{yyyy-MM-dd HH:mm:ss} level=%-5level logger=%logger{36}.%M:%L msg="%msg"%n
logging.pattern.file=time=%d{yyyy-MM-dd HH:mm:ss} level=%-5level logger=%logger{36}.%M:%L msg="%msg"%n
logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=INFO

logging.level.org.springframework=INFO
#logging.level.com.netflix.discovery=DEBUG
logging.level.org.springframework.web.client.RestTemplate=ERROR
logging.level.org.springframework.cloud=ERROR
logging.level.org.springframework.data.repository.config.RepositoryConfigurationDelegate=WARN
logging.level.org.springframework.web.HttpLogging=ERROR
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=1000
logging.logback.rollingpolicy.file-name-pattern=./stack-sentinel-%d{yyyy-MM-dd}.%i.log
logging.level.org.hibernate.SQL=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.security=INFO
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=INFO
logging.level.org.springframework.web.servlet.DispatcherServlet=INFO
logging.level.org.springframework.data.redis.core.RedisConnectionUtils=INFO
logging.level.org.springframework.data.repository.config.RepositoryConfigurationExtensionSupport=WARN

management.endpoints.web.exposure.include=health,info
management.health.diskspace.enabled=false
above.bytes.cc.users=cngabi@abovebytes.com

